/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JDBC;

import java.sql.*;

public class App
{
	public static void main(String[] args) throws ClassNotFoundException, SQLException
	{
		String	url		= "jdbc:mysql://localhost:3306/zechi?" + "autoReconnect=true&useSSL=false";
		String	uname	= "root";
		String	pass	= "";
		String	query	= "SELECT * FROM cats";
		
		Class.forName("com.mysql.jdbc.Driver");
		Connection	con	= DriverManager.getConnection(url, uname, pass);
		Statement	st	= con.createStatement();
		ResultSet	rs	= st.executeQuery(query);
		
		rs.next();
		String name = rs.getString("name");
		System.out.println("My name " + name);
		
		st.close();
		con.close();
	}//end main
}//end App - class
